In [ ]:
import numpy as np

#BASIC

In [ ]:
#> basic
a = np.array([1,2,3])
print(a) # prints the array
print(a.shape) # show the dimension and number of elements.
print(a.dtype) # prints the data type
print(a.size) # prints the size of the array
print(a.itemsize) # show the element size in bytes

[1 2 3]
(3,)
int64
3
8


Accessing elements

In [ ]:
print(a[0])

1


New array

In [ ]:
b = a * np.array([2,0,2])
print(b) # multiplies each of the element of array a with new array.

b = b + np.array([4])
print(b) # add 4 with each of the elemnt of the array.

b = b*2
print(b) # multiply 2 with each element.

[2 0 6]
[ 6  4 10]
[12  8 20]


List to Array

In [ ]:
list_1 = [1,2,3]
a = np.array(list_1)
print(a)

[1 2 3]


Root and log

In [ ]:
b = np.log(b)
print(b)

b = np.sqrt(b)
print(b)


[2.48490665 2.07944154 2.99573227]
[1.57635867 1.44202689 1.73081838]


Dot Product

In [ ]:
# we already have two array
dot = np.dot(a,b)
print(dot)

# another way
print(a @ b)

9.652867588884686
9.652867588884686


#Multidimensional Array

In [ ]:
a2  = np.array([[1,2],[3,4]])
print(a2)
print(a2.shape)
print(a2.ndim)

# access element.
print("elements", a2[0,1]) # prints individual elements 
print("elements", a2[0]) # print one row

[[1 2]
 [3 4]]
(2, 2)
2
elements 2
elements [1 2]


Matrix Operation

In [ ]:
print(a2.T) # print transpose
print(np.linalg.inv(a2))# prints inverse and remeber to keep it square matrix
print(np.linalg.det(a2)) # determinant
print(np.diag(a))# diagonal elements of the array


[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Indexing/ slicing / Boolean Indexing

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

#indexing
print("> 0,1 elements : ",arr[0,1])

# print element of the first row
print("> print the element of the first row :", arr[0,:])
print("> print the element of the second row :", arr[1,:])

# printing colums
print("> print the element of the first column :", arr[:,0])
print("> print the element of the second column :", arr[:,1])


print("> elements of row = 0 and column 1 to 3 :", arr[0,1:3])

# using the minus index

print("> last row and last element :", arr[-1,-1])
print(">  second > last row and last element :", arr[-1,-2])

[[1 2 3 4]
 [5 6 7 8]]
> 0,1 elements :  2
> print the element of the first row : [1 2 3 4]
> print the element of the second row : [5 6 7 8]
> print the element of the first column : [1 5]
> print the element of the second column : [2 6]
> elements of row = 0 and column 1 to 3 : [2 3]
> last row and last element : 8
>  second > last row and last element : 7


Condition on multidimenstional array.

In [ ]:
c = np.array([  [1,2], [3,4], [5,6] ])
print(c)

bool_idx = c>2
print(bool_idx) # it wil print the same matrx

print(c[c>2]) # prints all the elements of c which are greater than 2

d = np.array([12,23,4,3,2,46,332,87])
b = [1,2,3]
print(d[b]) # it prints the element of d with indexing of b elements. 

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[23  4  3]


# Reshaping

In [ ]:
ar = np.arange(1,7)
print(ar) # it actually gives out the array from range 1 to 6

# reshaping
print('befor reshaping ', ar.shape)
br = ar.reshape((2,3))
print('after reshaping ',br.shape) # if it fails to reshape, the it will throw an error. 
print(br) # transform into an array of 2,3

[1 2 3 4 5 6]
befor reshaping  (6,)
after reshaping  (2, 3)
[[1 2 3]
 [4 5 6]]


#Concatanation

In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[4,5],[6,7]])

c= np.concatenate((a1,a2)) # take in tuple
print(c)

# horizontal
c = np.hstack((a1,a2)) # row, column must match.
print(c)


# vertical
c = np.vstack((a1,a2)) # row, column must match.
print(c)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]
[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


#Broadcasting

In [ ]:
# to avoid error in during concatanation.

a1 = np.array([[1,2,5],[3,4,6],[12,12,7],[14,12,9]])
a2 = np.array([[1,1,0]])

y1 = a1 + a2
print(y1)

[[ 2  3  5]
 [ 4  5  6]
 [13 13  7]
 [15 13  9]]


# Function and axis

In [ ]:
sum1 = np.array([[1,2,5],[3,4,6],[12,12,7],[14,12,9]])
print('array', sum1)
print(sum1.sum()) # overall sum
print('by row :',sum1.sum(axis = 1)) # sum by row
print('By column :',sum1.sum(axis = 0)) # sum by column 

# for mean
print('Overall mean :',sum1.mean()) # function like axis availble to mean.

array [[ 1  2  5]
 [ 3  4  6]
 [12 12  7]
 [14 12  9]]
87
by row : [ 8 13 31 35]
By column : [30 30 27]
7.25


#Generating array

In [ ]:
# generate arrays full of zero 
a = np.zeros((2,3))
print(a,'\n')

# with 1
print('with ones')
a = np.ones((2,3))
print(a,'\n')

# with specific value
a = np.full((2,3),5.0)
print(a,'\n')

#identity martrix
a = np.eye(3)
print(a,' > identity matrix\n')


# generating random numbers
a = np.random.random((3,2))
print(a,'> random value\n')

# generating random numbers range 1> 10
a = np.random.randint(1,10, size =(3,3))
print(a,'> random value with range 1 > 10\n')




[[0. 0. 0.]
 [0. 0. 0.]] 

with ones
[[1. 1. 1.]
 [1. 1. 1.]] 

[[5. 5. 5.]
 [5. 5. 5.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]  > identity matrix

[[0.87729145 0.56292458]
 [0.89884281 0.11266156]
 [0.43535783 0.73632137]] > random value

[[4 8 2]
 [8 9 5]
 [7 7 3]] > random value



#Load CSV FILE

In [ ]:
# bring the data in the same file

data = np.genfromtxt("csv_file_name.csv", delimiter = ',')