# *** K Fold Cross Validation***

Cross validation allows us to see which model is performing better among multiple model, for example, supppose you used svm, or linear regression, using cross validation you can see whcih model is performing better.

It ensures that the score of our model does not depend on the way we select our train and test subsets. In this approach, we divide the data set into k number of subsets and the holdout method is repeated k number of times

In some cases we use tain and split method to test, in some cases we also use to train with all the data we have and perform the opertation. But both of them has some flaws like,being bias or for train and split, the splited data is completely different form the actual data.

In k cross validation , what we do is, we split our data in train and split fold, then first we take one fold and take the score of accuracy, then we take another fold and check the number of acuracy, if needed we do this again and check the number of acuracy. Then we avarage them out and take the average score. 

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt


In [3]:
digits = load_digits()

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

Using logistic regression

In [ ]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

In [8]:
lr.score(X_test, y_test)

0.9574074074074074

SVM

In [12]:
svm = SVC(gamma = "auto")
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.5166666666666667

Random Forest

In [13]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

K fold demonstration

In [14]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) # specified the number of folds you want to create.
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

# you can see it divided it into 3 folds or split , for test and train. 

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [19]:
# easy way for getting all the classifier result
print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))

0.9574074074074074


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [21]:
from sklearn.model_selection import StratifiedKFold
# StratifiedKFold : divide each of the classification category , in each fold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []


In [22]:
for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]

# appending scores of different model
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))

    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [23]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [26]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [25]:
scores_rf

[0.9398998330550918, 0.9549248747913188, 0.9298831385642737]

cross_val_score function(easy way)


In [27]:
from sklearn.model_selection import cross_val_score


For logisitic regression

In [28]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)


array([0.89482471, 0.95325543, 0.90984975])

svm model performance using cross_val_score



In [30]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

For random forest

In [33]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3) # with 40

array([0.92988314, 0.94657763, 0.9148581 ])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target,cv=3)# with 50 trees

# you can tune so that you can find various ways.

array([0.92487479, 0.94490818, 0.92654424])